/* automatically generated by rust-bindgen 0.73.2 */

pub const PWF_VERSION_MAJOR: u32 = 0;
pub const PWF_VERSION_MINOR: u32 = 12;
pub const PWF_VERSION_PATCH: u32 = 0;
pub const PWF_LOG_ERROR: pwf_log_level = 0;
pub const PWF_LOG_WARNING: pwf_log_level = 1;
pub const PWF_LOG_INFO: pwf_log_level = 2;
pub const PWF_LOG_DEBUG: pwf_log_level = 3;
pub const PWF_LOG_VERBOSE: pwf_log_level = 4;
pub type pwf_log_level = ::core::ffi::c_uint;
pub type pwf_log_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        level: pwf_log_level,
        file: *const ::core::ffi::c_char,
        line: ::core::ffi::c_int,
        message: *const ::core::ffi::c_char,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
unsafe extern "C" {
    pub fn pwf_log_set_callback(callback: pwf_log_func_t, user_data: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn pwf_log_set_level(level: pwf_log_level);
}
#[doc = "< Raw audio samples."]
pub const PWF_DATA_AUDIO: pwf_data_type = 0;
#[doc = "< Raw video frames."]
pub const PWF_DATA_VIDEO: pwf_data_type = 1;
#[doc = "< One 32-bit float per frame, e.g. a sensor reading; filter ports only, see pwf_filter.h."]
pub const PWF_DATA_SIGNAL: pwf_data_type = 2;
#[doc = "< Discrete timestamped items such as MIDI or a property; filter ports only, see pwf_filter.h."]
pub const PWF_DATA_EVENT: pwf_data_type = 3;
#[doc = " @brief Classifies a stream, or a pwf_filter_* port, by the kind of data\n        it carries.\n\n Audio and video are media; a signal and an event are not, which is why\n this is a data type. SIGNAL and EVENT are filter-port-only:\n pwf_stream_create() only accepts AUDIO/VIDEO and rejects the other two."]
pub type pwf_data_type = ::core::ffi::c_uint;
#[doc = "< Success."]
pub const PWF_OK: pwf_error = 0;
#[doc = "< A NULL/out-of-range argument, or a call invalid for the object's current state or routing mode."]
pub const PWF_ERR_INVALID_ARG: pwf_error = -1;
#[doc = "< Connecting to PipeWire, or asking it to create a stream, link or query, failed."]
pub const PWF_ERR_CONNECT_FAILED: pwf_error = -2;
#[doc = "< An unrecognized pixel/sample format string, or an out-of-range dimension/rate."]
pub const PWF_ERR_INVALID_FORMAT: pwf_error = -3;
#[doc = "< Called before a required prior step, e.g. start() before a format was set, link() before start(), or unlink() with nothing linked."]
pub const PWF_ERR_NOT_CONFIGURED: pwf_error = -4;
#[doc = "< The connected source disappeared, or could not provide the requested memory type (see pwf_stream_error_func_t)."]
pub const PWF_ERR_SOURCE_UNAVAILABLE: pwf_error = -5;
#[doc = "< Called from inside one of the object's own callbacks, where the call cannot run; call it again after the callback returns."]
pub const PWF_ERR_IN_CALLBACK: pwf_error = -6;
#[doc = "< No node in the graph matches the target name or serial; it may have gone away or never existed."]
pub const PWF_ERR_NOT_FOUND: pwf_error = -7;
#[doc = "< PipeWire did not answer, or a link did not negotiate, within the library's time limit; the same call may succeed if retried."]
pub const PWF_ERR_TIMEOUT: pwf_error = -8;
#[doc = "< A memory allocation failed."]
pub const PWF_ERR_NO_MEMORY: pwf_error = -9;
#[doc = " @brief Library error codes. Negative values only; 0 is success."]
pub type pwf_error = ::core::ffi::c_int;
#[doc = " @brief Audio capture configuration passed to\n        pwf_stream_set_audio_config() and pwf_filter_add_audio_port()."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_audio_config {
    #[doc = "< Hz, e.g. 48000."]
    pub sample_rate: ::core::ffi::c_int,
    #[doc = "< Channel count, e.g. 2."]
    pub channels: ::core::ffi::c_int,
    #[doc = "< \"U8\", \"S16\", \"S24\", \"S24_32\", \"S32\", or \"F32\"; NULL defaults to \"S16\"."]
    pub format: *const ::core::ffi::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_audio_config"][::core::mem::size_of::<pwf_audio_config>() - 16usize];
    ["Alignment of pwf_audio_config"][::core::mem::align_of::<pwf_audio_config>() - 8usize];
    ["Offset of field: pwf_audio_config::sample_rate"]
        [::core::mem::offset_of!(pwf_audio_config, sample_rate) - 0usize];
    ["Offset of field: pwf_audio_config::channels"]
        [::core::mem::offset_of!(pwf_audio_config, channels) - 4usize];
    ["Offset of field: pwf_audio_config::format"]
        [::core::mem::offset_of!(pwf_audio_config, format) - 8usize];
};
impl Default for pwf_audio_config {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " @brief Video capture configuration passed to pwf_stream_set_video_config()."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_video_config {
    #[doc = "< Frame width in pixels."]
    pub width: ::core::ffi::c_int,
    #[doc = "< Frame height in pixels."]
    pub height: ::core::ffi::c_int,
    #[doc = "< \"RGB\", \"YUYV\", \"NV12\", \"NV21\", \"I420\", \"MJPG\", or \"H264\". MJPG and H264 are compressed: each delivered frame's size varies, and DMABUF delivery is not available for them."]
    pub pixel_format: *const ::core::ffi::c_char,
    #[doc = "< Frames per second; 0 negotiates automatically."]
    pub fps: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_video_config"][::core::mem::size_of::<pwf_video_config>() - 24usize];
    ["Alignment of pwf_video_config"][::core::mem::align_of::<pwf_video_config>() - 8usize];
    ["Offset of field: pwf_video_config::width"]
        [::core::mem::offset_of!(pwf_video_config, width) - 0usize];
    ["Offset of field: pwf_video_config::height"]
        [::core::mem::offset_of!(pwf_video_config, height) - 4usize];
    ["Offset of field: pwf_video_config::pixel_format"]
        [::core::mem::offset_of!(pwf_video_config, pixel_format) - 8usize];
    ["Offset of field: pwf_video_config::fps"]
        [::core::mem::offset_of!(pwf_video_config, fps) - 16usize];
};
impl Default for pwf_video_config {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = "< Graph-selected, normally CPU-mapped."]
pub const PWF_PORT_MEMORY_AUTO: pwf_port_memory = 0;
#[doc = "< Negotiate DMABUF file descriptors."]
pub const PWF_PORT_MEMORY_DMABUF: pwf_port_memory = 1;
#[doc = " @brief Selects a video port/stream's buffer memory.\n\n AUTO is the default (graph-selected, normally CPU-mapped). DMABUF\n negotiates file descriptors instead of a CPU buffer."]
pub type pwf_port_memory = ::core::ffi::c_uint;
#[doc = " @brief One plane of a DMABUF-delivered frame.\n\n `fd` is borrowed (import-only, not owned): valid only for the callback\n that received it, do not close it."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct pwf_dmabuf_plane {
    #[doc = "< Borrowed DMABUF file descriptor; do not close."]
    pub fd: ::core::ffi::c_int,
    #[doc = "< Byte offset to the plane within the dmabuf."]
    pub offset: u32,
    #[doc = "< Row stride in bytes."]
    pub stride: u32,
    #[doc = "< Valid bytes of this plane."]
    pub size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_dmabuf_plane"][::core::mem::size_of::<pwf_dmabuf_plane>() - 16usize];
    ["Alignment of pwf_dmabuf_plane"][::core::mem::align_of::<pwf_dmabuf_plane>() - 4usize];
    ["Offset of field: pwf_dmabuf_plane::fd"]
        [::core::mem::offset_of!(pwf_dmabuf_plane, fd) - 0usize];
    ["Offset of field: pwf_dmabuf_plane::offset"]
        [::core::mem::offset_of!(pwf_dmabuf_plane, offset) - 4usize];
    ["Offset of field: pwf_dmabuf_plane::stride"]
        [::core::mem::offset_of!(pwf_dmabuf_plane, stride) - 8usize];
    ["Offset of field: pwf_dmabuf_plane::size"]
        [::core::mem::offset_of!(pwf_dmabuf_plane, size) - 12usize];
};
#[doc = " @brief One pixel format and frame size a target can deliver.\n\n Every field goes straight into a struct pwf_video_config; a pixel format this\n library cannot name is left out rather than reported as unusable. A\n device taking a range of sizes reports its ends, so `width_max`/\n `height_max` exceed `width`/`height` there and equal them otherwise."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, PartialEq, Eq)]
pub struct pwf_video_format_info {
    #[doc = "< \"RGB\", \"YUYV\", \"NV12\", \"NV21\", \"I420\", \"MJPG\", or \"H264\", as struct pwf_video_config takes it."]
    pub pixel_format: [::core::ffi::c_char; 16usize],
    #[doc = "< Frame width in pixels, or the smallest one for a size range."]
    pub width: ::core::ffi::c_int,
    #[doc = "< Frame height in pixels, or the smallest one for a size range."]
    pub height: ::core::ffi::c_int,
    #[doc = "< Equal to `width` for a discrete size, the range's largest width otherwise."]
    pub width_max: ::core::ffi::c_int,
    #[doc = "< Equal to `height` for a discrete size, the range's largest height otherwise."]
    pub height_max: ::core::ffi::c_int,
    #[doc = "< Frame rates at this size, highest first; whole frames per second, as struct pwf_video_config takes them."]
    pub fps: [::core::ffi::c_int; 8usize],
    #[doc = "< Entries set in `fps`, never more than it holds; a device offering more keeps its fastest rates."]
    pub n_fps: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_video_format_info"][::core::mem::size_of::<pwf_video_format_info>() - 72usize];
    ["Alignment of pwf_video_format_info"]
        [::core::mem::align_of::<pwf_video_format_info>() - 8usize];
    ["Offset of field: pwf_video_format_info::pixel_format"]
        [::core::mem::offset_of!(pwf_video_format_info, pixel_format) - 0usize];
    ["Offset of field: pwf_video_format_info::width"]
        [::core::mem::offset_of!(pwf_video_format_info, width) - 16usize];
    ["Offset of field: pwf_video_format_info::height"]
        [::core::mem::offset_of!(pwf_video_format_info, height) - 20usize];
    ["Offset of field: pwf_video_format_info::width_max"]
        [::core::mem::offset_of!(pwf_video_format_info, width_max) - 24usize];
    ["Offset of field: pwf_video_format_info::height_max"]
        [::core::mem::offset_of!(pwf_video_format_info, height_max) - 28usize];
    ["Offset of field: pwf_video_format_info::fps"]
        [::core::mem::offset_of!(pwf_video_format_info, fps) - 32usize];
    ["Offset of field: pwf_video_format_info::n_fps"]
        [::core::mem::offset_of!(pwf_video_format_info, n_fps) - 64usize];
};
#[doc = " @brief Opaque handle to one audio- or video-capture stream."]
#[repr(C)]
#[derive(Debug)]
pub struct pwf_stream {
    _unused: [u8; 0],
}
#[doc = " @brief One delivered buffer of captured audio samples or a video frame.\n\n A struct (rather than loose parameters) so future fields can be added\n without changing pwf_stream_data_func_t's signature. `data`/`size`/`pts` are\n valid only for the duration of the data callback."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_stream_buffer {
    #[doc = "< Captured bytes, or NULL when the stream negotiated DMABUF (see pwf_stream_get_dmabuf_planes())."]
    pub data: *mut ::core::ffi::c_void,
    #[doc = "< Bytes available at `data`; 0 when `data` is NULL."]
    pub size: usize,
    #[doc = "< Capture timestamp in nanoseconds (the driver clock used by the underlying SPA node, e.g. ALSA or V4L2), or -1 if the buffer carried no timestamp metadata."]
    pub pts: i64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_stream_buffer"][::core::mem::size_of::<pwf_stream_buffer>() - 24usize];
    ["Alignment of pwf_stream_buffer"][::core::mem::align_of::<pwf_stream_buffer>() - 8usize];
    ["Offset of field: pwf_stream_buffer::data"]
        [::core::mem::offset_of!(pwf_stream_buffer, data) - 0usize];
    ["Offset of field: pwf_stream_buffer::size"]
        [::core::mem::offset_of!(pwf_stream_buffer, size) - 8usize];
    ["Offset of field: pwf_stream_buffer::pts"]
        [::core::mem::offset_of!(pwf_stream_buffer, pts) - 16usize];
};
impl Default for pwf_stream_buffer {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " @brief Delivers one buffer of captured audio samples or a video frame.\n\n Runs on PipeWire's real-time data thread, so it must not block. Calls that\n take the stream's loop lock are refused here with PWF_ERR_IN_CALLBACK:\n start, stop, link, unlink, the target queries and the format setters.\n pwf_stream_destroy() is refused as well and only logs, so destroy the\n stream after the callback returns.\n\n @param stream    The stream that produced `buf`.\n @param buf       This cycle's buffer; valid only for the duration of this call.\n @param user_data The pointer passed to pwf_stream_create()."]
pub type pwf_stream_data_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        stream: *mut pwf_stream,
        buf: *const pwf_stream_buffer,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
#[doc = " @brief One cycle's writable region for a playback stream.\n\n `data`, `available` and `pts` are set by the library; the callback sets\n `size`."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_stream_playback_buffer {
    #[doc = "< Writable region for this cycle, never NULL."]
    pub data: *mut ::core::ffi::c_void,
    #[doc = "< Bytes the callback may write this cycle: what the device asked for, or the region's full size when the graph states no request. Not the region's capacity — it is usually smaller."]
    pub available: usize,
    #[doc = "< When this cycle's first sample is expected to be heard, in monotonic nanoseconds, or -1 if the graph cannot state one. The mirror of the capture buffer's pts, not the same thing: capture reports when samples were taken, playback when they will be played."]
    pub pts: i64,
    #[doc = "< Set by the callback: bytes actually written. Clamped to `available` and floored to whole frames; the remainder up to `available` is emitted as silence, so 0 emits a silent cycle rather than stopping."]
    pub size: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_stream_playback_buffer"]
        [::core::mem::size_of::<pwf_stream_playback_buffer>() - 32usize];
    ["Alignment of pwf_stream_playback_buffer"]
        [::core::mem::align_of::<pwf_stream_playback_buffer>() - 8usize];
    ["Offset of field: pwf_stream_playback_buffer::data"]
        [::core::mem::offset_of!(pwf_stream_playback_buffer, data) - 0usize];
    ["Offset of field: pwf_stream_playback_buffer::available"]
        [::core::mem::offset_of!(pwf_stream_playback_buffer, available) - 8usize];
    ["Offset of field: pwf_stream_playback_buffer::pts"]
        [::core::mem::offset_of!(pwf_stream_playback_buffer, pts) - 16usize];
    ["Offset of field: pwf_stream_playback_buffer::size"]
        [::core::mem::offset_of!(pwf_stream_playback_buffer, size) - 24usize];
};
impl Default for pwf_stream_playback_buffer {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " @brief Asks the application to fill one cycle of audio.\n\n Runs on the real-time data thread: it MUST NOT block, allocate, or\n perform I/O. A cycle whose callback runs past its budget is emitted as\n silence and recorded in the library log, not reported through\n pwf_stream_error_func_t. The calls pwf_stream_data_func_t refuses are refused here too.\n\n @param stream    The playback stream asking for data.\n @param buf       This cycle's writable region; valid only for the duration of this call.\n @param user_data The pointer passed to pwf_stream_create_playback()."]
pub type pwf_stream_playback_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        stream: *mut pwf_stream,
        buf: *mut pwf_stream_playback_buffer,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
#[doc = " @brief Reports that `stream`'s source became unavailable while running.\n\n Runs on the stream's loop thread. A stop without drain and\n pwf_stream_unlink() work here, but calls that would wait on this same\n thread are refused with PWF_ERR_IN_CALLBACK: a draining stop, link,\n the target queries and the format setters. pwf_stream_destroy() is refused\n and only logs, so re-route or destroy the stream after the callback returns.\n\n @param stream     The affected stream.\n @param error_code An enum pwf_error, currently always PWF_ERR_SOURCE_UNAVAILABLE.\n @param user_data  The pointer passed to pwf_stream_create()/pwf_stream_create_playback()."]
pub type pwf_stream_error_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        stream: *mut pwf_stream,
        error_code: ::core::ffi::c_int,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
unsafe extern "C" {
    #[doc = " @brief Creates a stream of `type`.\n\n Owns and manages its own PipeWire thread-loop/context/core internally.\n\n @param type      PWF_DATA_AUDIO or PWF_DATA_VIDEO; SIGNAL/EVENT are rejected.\n @param callback  Invoked with each delivered buffer once the stream is started.\n @param user_data Passed unchanged to `callback`.\n @return A new stream handle, or NULL if PipeWire cannot be reached or `type` is rejected."]
    pub fn pwf_stream_create(
        type_: pwf_data_type,
        callback: pwf_stream_data_func_t,
        user_data: *mut ::core::ffi::c_void,
    ) -> *mut pwf_stream;
}
unsafe extern "C" {
    #[doc = " @brief Creates an audio playback stream, emitting to an output device\n        instead of capturing from an input one.\n\n Audio only: with no media type parameter a video playback stream cannot\n be expressed. Owns its own PipeWire thread-loop/context/core and fails\n fast exactly as pwf_stream_create() does. The result is used with the\n same set_error_callback/set_target/set_audio_config/start/stop/destroy calls;\n pwf_stream_set_video_config() is rejected on it.\n\n @param callback  Invoked once per cycle to fill the next block of audio.\n @param user_data Passed unchanged to `callback`.\n @return A new playback stream handle, or NULL if PipeWire cannot be reached."]
    pub fn pwf_stream_create_playback(
        callback: pwf_stream_playback_func_t,
        user_data: *mut ::core::ffi::c_void,
    ) -> *mut pwf_stream;
}
unsafe extern "C" {
    #[doc = " @brief Registers (or clears, with NULL) the optional async-error callback.\n @param stream   The stream to configure.\n @param callback The callback to invoke on source loss, or NULL to clear it.\n @return PWF_OK, or PWF_ERR_INVALID_ARG for a NULL `stream`."]
    pub fn pwf_stream_set_error_callback(
        stream: *mut pwf_stream,
        callback: pwf_stream_error_func_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Sets (or clears, with NULL) the PipeWire node this stream should\n        connect to, by name or serial (as shown by `wpctl status` or\n        `pw-cli ls Node`).\n\n Call it before pwf_stream_set_audio_config()/\n pwf_stream_set_video_config(), which is what actually connects the\n stream; a target set after that is kept but never read. If never\n called, the stream auto-connects to PipeWire's default source for its\n media type. This is a hint to the session manager, which does the\n wiring, so it means nothing while autoconnect is off: naming a target\n then is refused, though clearing with NULL is always accepted.\n\n @param stream The stream to target, before its format is set.\n @param target A node name or object.serial, or NULL to clear a previously set target.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL `stream` or for a non-NULL `target` while autoconnect is off, or PWF_ERR_NO_MEMORY when the name cannot be copied."]
    pub fn pwf_stream_set_target(
        stream: *mut pwf_stream,
        target: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Sets (or clears, with NULL) the media role this stream declares,\n        such as \"Music\", \"Movie\", \"Communication\" or \"Notification\".\n\n Like a target, it is a hint to the session manager's role policy and is\n read when pwf_stream_set_audio_config()/pwf_stream_set_video_config()\n connects the stream, so a role set later does not reach that node.\n Nothing acts on it without such a policy, which is why it is accepted\n whatever the autoconnect setting, where a target is not.\n\n @param stream The stream to label, before its format is set.\n @param role   A role name, or NULL to clear a previously set role.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL `stream`, or PWF_ERR_NO_MEMORY when the role cannot be copied."]
    pub fn pwf_stream_set_role(
        stream: *mut pwf_stream,
        role: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
#[doc = " @brief One target pwf_stream_set_target()/pwf_stream_link() would\n        accept, discovered from the running graph."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_target_info {
    #[doc = "< Node name, usable directly as a target string."]
    pub name: [::core::ffi::c_char; 256usize],
    #[doc = "< The node's object.serial as decimal digits, also usable directly as a target string — an alternative to `name` when two nodes share one."]
    pub serial: [::core::ffi::c_char; 32usize],
    #[doc = "< Human-readable node.description (what wpctl status shows), or \"\" if the node never set one."]
    pub description: [::core::ffi::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_target_info"][::core::mem::size_of::<pwf_target_info>() - 544usize];
    ["Alignment of pwf_target_info"][::core::mem::align_of::<pwf_target_info>() - 1usize];
    ["Offset of field: pwf_target_info::name"]
        [::core::mem::offset_of!(pwf_target_info, name) - 0usize];
    ["Offset of field: pwf_target_info::serial"]
        [::core::mem::offset_of!(pwf_target_info, serial) - 256usize];
    ["Offset of field: pwf_target_info::description"]
        [::core::mem::offset_of!(pwf_target_info, description) - 288usize];
};
impl Default for pwf_target_info {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " @brief Lists targets pwf_stream_set_target()/pwf_stream_link() would\n        accept for `stream`'s own media type and direction.\n\n A capture stream lists sources, a playback stream lists sinks — the\n same distinction `wpctl status`/`pw-cli ls Node` show as a node's\n media.class. Requires a live PipeWire connection; a freshly created\n stream binds the registry and waits for the graph's initial burst of\n globals on its first call.\n\n @param[in]  stream  Selects which targets qualify, by its own type/direction.\n @param[out] out     Filled with up to `out_len` targets, or NULL to only count them.\n @param[in]  out_len Capacity of `out`.\n @param[out] found   The target count actually available, which may exceed `out_len` if it was too small; 0 on failure. A graph with no such node is PWF_OK with 0, not an error.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL `stream` or `found`, PWF_ERR_IN_CALLBACK from inside a callback, PWF_ERR_TIMEOUT when the registry does not answer in time, or PWF_ERR_CONNECT_FAILED when it cannot be reached."]
    pub fn pwf_stream_get_target_list(
        stream: *mut pwf_stream,
        out: *mut pwf_target_info,
        out_len: usize,
        found: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Lists the video formats `target` can deliver to `stream`.\n\n Call it between pwf_stream_set_target() and\n pwf_stream_set_video_config(). Every entry is one that setter accepts\n for that target, so passing one on cannot fail for want of support.\n Reading a device's formats opens it briefly, unlike the free lookup\n pwf_stream_get_target_list() does.\n\n @param[in]  stream  A video capture stream, which supplies the connection.\n @param[in]  target  A node name or object.serial, or NULL for the target already set with pwf_stream_set_target().\n @param[out] out     Filled with up to `out_len` formats, or NULL to only count them.\n @param[in]  out_len Capacity of `out`.\n @param[out] found   The format count actually available, which may exceed `out_len` if it was too small; 0 on failure. A device reporting no format this library can name is PWF_OK with 0, not an error.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL or non-video stream, a NULL `found`, or no target to read, PWF_ERR_NOT_FOUND for a target naming no node, PWF_ERR_IN_CALLBACK from inside a callback, PWF_ERR_TIMEOUT when the query does not answer in time, or PWF_ERR_CONNECT_FAILED when it fails."]
    pub fn pwf_stream_get_target_video_formats(
        stream: *mut pwf_stream,
        target: *const ::core::ffi::c_char,
        out: *mut pwf_video_format_info,
        out_len: usize,
        found: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Turns automatic connection off, so the application wires the\n        stream itself with pwf_stream_link().\n\n On by default, which is what every existing caller already gets. Must\n be called before the format is set; the routing mode is fixed once the\n stream connects. Mutually exclusive with a target rather than with the\n setter: turning autoconnect off while one is set is refused, as is\n naming a target while it is off. Clear the target with\n pwf_stream_set_target(NULL) to move from either to the other.\n\n @param stream The stream to configure, before its format is set.\n @param enable false to opt out of autoconnect (manual wiring via pwf_stream_link()); true puts the stream back under the session manager, and leaves any target already set in place.\n @return PWF_OK, or PWF_ERR_INVALID_ARG for a NULL `stream`, a format already set, or `enable` false while a target is set."]
    pub fn pwf_stream_set_autoconnect(stream: *mut pwf_stream, enable: bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Connects every channel of `stream` to `target` — a node name or\n        an object.serial — with PipeWire core links, needing no session\n        manager.\n\n Channels are paired by position, so a stereo stream reaches a stereo\n device's two ports without the caller naming any of them.\n\n Requires autoconnect to be off, and must be called after\n pwf_stream_start(): the target and the stream's own ports are both\n resolved in the running graph, and the ports appear shortly after the\n stream starts. Blocks until every link negotiates; on any channel\n failing, none is left behind.\n\n A device offering more channels than the stream has is not an error:\n the surplus stay unconnected and the condition is logged, since a mono\n stream reaching one side of a stereo device looks like a fault. A\n device offering fewer is rejected outright.\n\n @param stream The running stream to wire, with autoconnect off.\n @param target A node name or an object.serial.\n @return PWF_OK, or an enum pwf_error: NOT_CONFIGURED before start, INVALID_ARG for a bad mode, target string or channel count or an already-linked stream, NOT_FOUND for a target naming no node, IN_CALLBACK from inside a callback, TIMEOUT when the stream's ports or a link do not appear in time, INVALID_FORMAT when a link fails to negotiate, NO_MEMORY when an allocation fails, CONNECT_FAILED when a link cannot be created."]
    pub fn pwf_stream_link(
        stream: *mut pwf_stream,
        target: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Releases every link created on `stream`.\n\n pwf_stream_destroy() does this itself, so an explicit call is only\n needed to re-target a stream. pwf_stream_stop() deliberately does NOT\n release: a stopped stream resumes on the same device when started\n again.\n\n @param stream The stream to unlink.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL `stream`, PWF_ERR_NOT_CONFIGURED when the stream has no links, or PWF_ERR_IN_CALLBACK from its data callback."]
    pub fn pwf_stream_unlink(stream: *mut pwf_stream) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Configures audio format before starting an audio stream.\n @param stream The stream to configure; must not have started yet.\n @param config The requested sample rate, channel count, and sample format.\n @return PWF_OK, PWF_ERR_INVALID_ARG (NULL stream/config, or not an audio stream), PWF_ERR_INVALID_FORMAT (unrecognized format or out-of-range field), PWF_ERR_IN_CALLBACK (from inside a callback), or PWF_ERR_CONNECT_FAILED."]
    pub fn pwf_stream_set_audio_config(
        stream: *mut pwf_stream,
        config: *const pwf_audio_config,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Configures video format before starting a video stream.\n @param stream The stream to configure; must not have started yet.\n @param config The requested width, height, pixel format, and frame rate.\n @return PWF_OK, PWF_ERR_INVALID_ARG (NULL stream/config, or not a video-capture stream), PWF_ERR_INVALID_FORMAT (unrecognized pixel format or out-of-range dimension), PWF_ERR_IN_CALLBACK (from inside a callback), or PWF_ERR_CONNECT_FAILED."]
    pub fn pwf_stream_set_video_config(
        stream: *mut pwf_stream,
        config: *const pwf_video_config,
    ) -> ::core::ffi::c_int;
}
#[doc = " @brief Per-stream DMABUF options.\n\n A NULL or zeroed struct means AUTO, i.e. the behavior of\n pwf_stream_set_video_config()."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_stream_dmabuf_opts {
    #[doc = "< AUTO (default) or DMABUF."]
    pub memory: pwf_port_memory,
    #[doc = "< Must be zero; reserved for future options."]
    pub reserved: [u32; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_stream_dmabuf_opts"][::core::mem::size_of::<pwf_stream_dmabuf_opts>() - 12usize];
    ["Alignment of pwf_stream_dmabuf_opts"]
        [::core::mem::align_of::<pwf_stream_dmabuf_opts>() - 4usize];
    ["Offset of field: pwf_stream_dmabuf_opts::memory"]
        [::core::mem::offset_of!(pwf_stream_dmabuf_opts, memory) - 0usize];
    ["Offset of field: pwf_stream_dmabuf_opts::reserved"]
        [::core::mem::offset_of!(pwf_stream_dmabuf_opts, reserved) - 4usize];
};
impl Default for pwf_stream_dmabuf_opts {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " @brief Configures video format before starting a video capture stream,\n        with options.\n\n Equivalent to pwf_stream_set_video_config() when `opts` is NULL. With\n opts->memory == PWF_PORT_MEMORY_DMABUF, the stream negotiates DMABUF\n frames: pwf_stream_buffer.data is NULL for each delivered frame and\n planes are read via pwf_stream_get_dmabuf_planes(). Video capture only —\n the same type/direction rejection as pwf_stream_set_video_config()\n applies, so calling this on an audio or playback stream returns\n PWF_ERR_INVALID_ARG.\n\n If the source cannot provide DMABUF, negotiation fails asynchronously:\n the condition is logged and pwf_stream_error_func_t (if set) is invoked\n with PWF_ERR_SOURCE_UNAVAILABLE, the same path used when a\n source is lost after connecting. The stream delivers no frames until\n reconfigured without DMABUF.\n\n config->pixel_format == \"MJPG\" combined with DMABUF is rejected right\n away with PWF_ERR_INVALID_ARG instead: that combination never\n works, so it fails immediately rather than through the async path above.\n\n @param stream The stream to configure; must not have started yet.\n @param config The requested width, height, pixel format, and frame rate.\n @param opts   DMABUF options, or NULL for AUTO.\n @return PWF_OK, PWF_ERR_INVALID_ARG (NULL stream/config, not a video-capture stream, or MJPG requested with DMABUF), PWF_ERR_INVALID_FORMAT, PWF_ERR_IN_CALLBACK (from inside a callback), or PWF_ERR_CONNECT_FAILED."]
    pub fn pwf_stream_set_video_config_ex(
        stream: *mut pwf_stream,
        config: *const pwf_video_config,
        opts: *const pwf_stream_dmabuf_opts,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Fills up to `planes_len` entries of `planes` with the current\n        cycle's DMABUF frame layout.\n\n Valid only during the data callback (pwf_stream_data_func_t). `planes`\n comes before `planes_len`, its own capacity, rather than after,\n keeping the array and its capacity adjacent even though `planes` is\n the out-parameter here.\n\n @param[in]  stream     The stream whose current-cycle buffer to read.\n @param[out] planes     Filled with up to `planes_len` planes, most-significant plane first.\n @param[in]  planes_len Capacity of `planes`.\n @return The plane count actually available, which may exceed `planes_len` if it was too small; 0 for a non-DMABUF stream or a cycle with no buffer, and `planes` is left unwritten."]
    pub fn pwf_stream_get_dmabuf_planes(
        stream: *mut pwf_stream,
        planes: *mut pwf_dmabuf_plane,
        planes_len: usize,
    ) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Starts data delivery. Requires a format to already be set.\n @param stream The stream to start.\n @return PWF_OK, PWF_ERR_INVALID_ARG (NULL stream), PWF_ERR_IN_CALLBACK (from its data callback), PWF_ERR_NOT_CONFIGURED (no format set), or PWF_ERR_CONNECT_FAILED."]
    pub fn pwf_stream_start(stream: *mut pwf_stream) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Stops data delivery; the stream may be started again later.\n\n With `drain` true, blocks until every buffer already queued has\n actually been played (a playback stream) or delivered to the data\n callback (a capture stream), so nothing already queued is lost. If\n that does not complete within a few seconds (a lost device, for\n instance), a warning is logged and the stream stops anyway. It is refused\n from the data callback, and a draining stop from the error callback too.\n\n @param stream The stream to stop.\n @param drain  true to wait for what is already queued to finish first.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL `stream`, or PWF_ERR_IN_CALLBACK for a stop refused inside a callback."]
    pub fn pwf_stream_stop(stream: *mut pwf_stream, drain: bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Releases all resources owned by `stream`.\n\n Invalid for further use after this call, running or not. Called from inside\n one of the stream's own callbacks it only logs, since it would tear down the\n thread running that callback; the stream is left as it was.\n\n @param stream The stream to destroy; NULL is a no-op."]
    pub fn pwf_stream_destroy(stream: *mut pwf_stream);
}
#[doc = " @brief Opaque handle to one multi-port filter."]
#[repr(C)]
#[derive(Debug)]
pub struct pwf_filter {
    _unused: [u8; 0],
}
#[doc = " @brief Opaque handle to one input or output port on a filter."]
#[repr(C)]
#[derive(Debug)]
pub struct pwf_filter_port {
    _unused: [u8; 0],
}
#[doc = "< Consumes data delivered by the graph, or pushed with pwf_filter_push_port_data()/pwf_filter_port_push_event()."]
pub const PWF_FILTER_PORT_INPUT: pwf_filter_port_direction = 0;
#[doc = "< Produces data for the graph, written from the processing callback."]
pub const PWF_FILTER_PORT_OUTPUT: pwf_filter_port_direction = 1;
#[doc = " @brief Direction of a filter port."]
pub type pwf_filter_port_direction = ::core::ffi::c_uint;
#[doc = " @brief One port's buffer for a single processing cycle.\n\n `data`/`size`/`capacity`/`pts` are valid only for the duration of the\n process callback."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_filter_port_buffer {
    #[doc = "< Which port this entry describes."]
    pub port: *mut pwf_filter_port,
    #[doc = "< NULL if no buffer was available this cycle."]
    pub data: *mut ::core::ffi::c_void,
    #[doc = "< Input: bytes available to read. Output: bytes to publish; set by the callback before returning (0 = no output this cycle)."]
    pub size: usize,
    #[doc = "< Output ports only: max bytes `data` can hold."]
    pub capacity: usize,
    #[doc = "< Input ports only: capture/presentation timestamp in nanoseconds from the source (e.g. an ALSA/V4L2 device's driver clock), or the value passed to pwf_filter_push_port_data() for pushed data. -1 if unavailable. Always -1 on output ports and on event ports (each struct pwf_event carries its own `offset` instead)."]
    pub pts: i64,
    #[doc = "< Input ports only: true only when this buffer is new this cycle; false for a held re-presentation (see pwf_filter_port_set_hold()) or a cycle with no buffer. Always false on output ports."]
    pub fresh: bool,
    #[doc = "< Input ports only: per-port update counter that advances only when new data arrives, so it is unchanged across held cycles and its deltas count genuinely new buffers."]
    pub seq: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_filter_port_buffer"][::core::mem::size_of::<pwf_filter_port_buffer>() - 56usize];
    ["Alignment of pwf_filter_port_buffer"]
        [::core::mem::align_of::<pwf_filter_port_buffer>() - 8usize];
    ["Offset of field: pwf_filter_port_buffer::port"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, port) - 0usize];
    ["Offset of field: pwf_filter_port_buffer::data"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, data) - 8usize];
    ["Offset of field: pwf_filter_port_buffer::size"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, size) - 16usize];
    ["Offset of field: pwf_filter_port_buffer::capacity"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, capacity) - 24usize];
    ["Offset of field: pwf_filter_port_buffer::pts"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, pts) - 32usize];
    ["Offset of field: pwf_filter_port_buffer::fresh"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, fresh) - 40usize];
    ["Offset of field: pwf_filter_port_buffer::seq"]
        [::core::mem::offset_of!(pwf_filter_port_buffer, seq) - 48usize];
};
impl Default for pwf_filter_port_buffer {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[doc = " @brief Invoked once per processing cycle with every port's buffer.\n\n Runs on PipeWire's real-time data thread, so it must not block. The push,\n event and DMABUF calls belong here, but calls that take the filter's loop\n lock are refused with PWF_ERR_IN_CALLBACK: start, stop, port link and\n unlink, and pwf_filter_get_target_video_formats(). pwf_filter_destroy() is\n refused too and only logs, so destroy the filter after the callback returns.\n\n @param filter    The filter running this cycle.\n @param buffers   One entry per port; valid only for the duration of this call.\n @param n_buffers Number of entries in `buffers`.\n @param user_data The pointer passed to pwf_filter_create()."]
pub type pwf_filter_process_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        filter: *mut pwf_filter,
        buffers: *mut pwf_filter_port_buffer,
        n_buffers: usize,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
#[doc = " @brief Reports that `port` on `filter` became unavailable while\n        running; the filter's other ports are unaffected.\n\n Runs on the filter's loop thread, once per source an input port loses, and\n never for the application's own unlink, stop or destroy. A stop without\n drain and pwf_filter_port_unlink() work here. A draining stop,\n pwf_filter_port_link() and pwf_filter_get_target_video_formats() would wait\n on this thread, so they are refused with PWF_ERR_IN_CALLBACK, and\n pwf_filter_destroy() is refused and only logs.\n\n @param filter     The filter owning `port`.\n @param port       The port that became unavailable.\n @param error_code An enum pwf_error, currently always PWF_ERR_SOURCE_UNAVAILABLE.\n @param user_data  The pointer passed to pwf_filter_create()."]
pub type pwf_filter_error_func_t = ::core::option::Option<
    unsafe extern "C" fn(
        filter: *mut pwf_filter,
        port: *mut pwf_filter_port,
        error_code: ::core::ffi::c_int,
        user_data: *mut ::core::ffi::c_void,
    ),
>;
#[doc = "< Real MIDI wire bytes."]
pub const PWF_EVENT_MIDI: pwf_event_kind = 0;
#[doc = "< Real OSC wire bytes."]
pub const PWF_EVENT_OSC: pwf_event_kind = 1;
#[doc = "< General-purpose named value; `key` selects it."]
pub const PWF_EVENT_PROPERTY: pwf_event_kind = 2;
#[doc = "< Read-only: an undecoded control item from another client."]
pub const PWF_EVENT_UNKNOWN: pwf_event_kind = 3;
#[doc = " @brief Which real wire kind an event carries.\n\n MIDI/OSC carry real MIDI/OSC wire bytes for interop with other\n PipeWire MIDI/OSC clients; PROPERTY is the general-purpose kind for\n anything else a caller writes. UNKNOWN is read-only: it appears only\n on an event pwf_filter_port_get_event() decoded from a control item\n this library doesn't recognize (for example, one written by some\n other PipeWire client using a control kind outside this set); `data`/\n `size` are that item's raw, undecoded value bytes, and `key` is NULL.\n Passing UNKNOWN to pwf_filter_port_push_event() is rejected."]
pub type pwf_event_kind = ::core::ffi::c_uint;
#[doc = " @brief One discrete, time-stamped item exchanged through an event port.\n\n `key` is meaningful only for PWF_EVENT_PROPERTY (a name from the\n supported property vocabulary) and MUST be NULL otherwise. Pointers\n are valid only for the duration of the processing callback (when read\n from pwf_filter_port_get_event()) or the call to\n pwf_filter_port_push_event() (the library copies what it needs from a\n pushed event)."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_event {
    #[doc = "< This event's position within the current cycle, in frames."]
    pub offset: u32,
    #[doc = "< MIDI, OSC, PROPERTY, or (read-only) UNKNOWN."]
    pub kind: pwf_event_kind,
    #[doc = "< Property name for PWF_EVENT_PROPERTY; NULL otherwise."]
    pub key: *const ::core::ffi::c_char,
    #[doc = "< MIDI/OSC: real wire-format bytes. PROPERTY: the value's raw bytes. UNKNOWN: the raw undecoded control value's bytes."]
    pub data: *const ::core::ffi::c_void,
    #[doc = "< Bytes at `data`."]
    pub size: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_event"][::core::mem::size_of::<pwf_event>() - 32usize];
    ["Alignment of pwf_event"][::core::mem::align_of::<pwf_event>() - 8usize];
    ["Offset of field: pwf_event::offset"][::core::mem::offset_of!(pwf_event, offset) - 0usize];
    ["Offset of field: pwf_event::kind"][::core::mem::offset_of!(pwf_event, kind) - 4usize];
    ["Offset of field: pwf_event::key"][::core::mem::offset_of!(pwf_event, key) - 8usize];
    ["Offset of field: pwf_event::data"][::core::mem::offset_of!(pwf_event, data) - 16usize];
    ["Offset of field: pwf_event::size"][::core::mem::offset_of!(pwf_event, size) - 24usize];
};
impl Default for pwf_event {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " @brief Creates an empty filter (no ports yet) whose node other\n        applications and pwf_filter_port_link() find by `name`.\n\n Internally owns and manages its own PipeWire thread-loop/context/core.\n\n @param name      The node's name (node.name); NULL or empty leaves PipeWire's default, the process name.\n @param callback  Invoked once per processing cycle after pwf_filter_start().\n @param user_data Passed unchanged to `callback`.\n @return A new filter handle, or NULL if PipeWire cannot be reached."]
    pub fn pwf_filter_create(
        name: *const ::core::ffi::c_char,
        callback: pwf_filter_process_func_t,
        user_data: *mut ::core::ffi::c_void,
    ) -> *mut pwf_filter;
}
unsafe extern "C" {
    #[doc = " @brief Registers (or clears, with NULL) the optional per-port\n        async-error callback.\n @param filter   The filter to configure.\n @param callback The callback to invoke on port loss, or NULL to clear it.\n @return PWF_OK, or PWF_ERR_INVALID_ARG for a NULL `filter`."]
    pub fn pwf_filter_set_error_callback(
        filter: *mut pwf_filter,
        callback: pwf_filter_error_func_t,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Adds one audio port (input or output) to `filter`.\n\n Must be called before pwf_filter_start(); adding ports after starting\n is unsupported.\n\n @param filter    The filter to add the port to, not yet started.\n @param direction PWF_FILTER_PORT_INPUT or PWF_FILTER_PORT_OUTPUT.\n @param config    The requested sample rate, channel count, and sample format.\n @return The new port handle, or NULL on invalid arguments or an unsupported format."]
    pub fn pwf_filter_add_audio_port(
        filter: *mut pwf_filter,
        direction: pwf_filter_port_direction,
        config: *const pwf_audio_config,
    ) -> *mut pwf_filter_port;
}
unsafe extern "C" {
    #[doc = " @brief Lists the video formats `target` can deliver to a port on `filter`.\n\n Call it before pwf_filter_add_video_port(), which fixes a port's format\n for good. A filter port carries no converter, unlike a pwf_stream, so a\n format the target lacks only surfaces as PWF_ERR_INVALID_FORMAT\n from pwf_filter_port_link(). Every entry here is one\n pwf_filter_add_video_port() accepts. Pass pwf_filter_port_link() the\n same `target` string; reading formats opens the device briefly.\n\n @param[in]  filter  Supplies the connection; need not be started yet.\n @param[in]  target  A node name, an object.serial, or \"node:port\"; the port part is accepted and ignored, as formats belong to the node.\n @param[out] out     Filled with up to `out_len` formats, or NULL to only count them.\n @param[in]  out_len Capacity of `out`.\n @param[out] found   The format count actually available, which may exceed `out_len` if it was too small; 0 on failure. A device reporting no format this library can name is PWF_OK with 0, not an error.\n @return PWF_OK, PWF_ERR_INVALID_ARG for a NULL filter, target or `found`, PWF_ERR_NOT_FOUND for a target naming no node, PWF_ERR_IN_CALLBACK from inside a callback, PWF_ERR_TIMEOUT when the query does not answer in time, or PWF_ERR_CONNECT_FAILED when it fails."]
    pub fn pwf_filter_get_target_video_formats(
        filter: *mut pwf_filter,
        target: *const ::core::ffi::c_char,
        out: *mut pwf_video_format_info,
        out_len: usize,
        found: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Adds one video port (input or output) to `filter`.\n\n Same timing and failure behavior as pwf_filter_add_audio_port().\n\n @param filter    The filter to add the port to, not yet started.\n @param direction PWF_FILTER_PORT_INPUT or PWF_FILTER_PORT_OUTPUT.\n @param config    The requested width, height, pixel format, and frame rate.\n @return The new port handle, or NULL on invalid arguments or an unsupported format."]
    pub fn pwf_filter_add_video_port(
        filter: *mut pwf_filter,
        direction: pwf_filter_port_direction,
        config: *const pwf_video_config,
    ) -> *mut pwf_filter_port;
}
#[doc = " @brief Extensible per-port options.\n\n A NULL or zeroed struct means AUTO, i.e. the behavior of the non-_ex\n add call. enum pwf_port_memory is declared in pwf_stream.h, shared with\n pwf_stream_get_dmabuf_planes()."]
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct pwf_filter_port_opts {
    #[doc = "< AUTO (default) or DMABUF."]
    pub memory: pwf_port_memory,
    #[doc = "< Must be zero; reserved for future options."]
    pub reserved: [u32; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pwf_filter_port_opts"][::core::mem::size_of::<pwf_filter_port_opts>() - 12usize];
    ["Alignment of pwf_filter_port_opts"][::core::mem::align_of::<pwf_filter_port_opts>() - 4usize];
    ["Offset of field: pwf_filter_port_opts::memory"]
        [::core::mem::offset_of!(pwf_filter_port_opts, memory) - 0usize];
    ["Offset of field: pwf_filter_port_opts::reserved"]
        [::core::mem::offset_of!(pwf_filter_port_opts, reserved) - 4usize];
};
impl Default for pwf_filter_port_opts {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    #[doc = " @brief Adds one video port with options.\n\n Equivalent to pwf_filter_add_video_port() when `opts` is NULL. With\n opts->memory == PWF_PORT_MEMORY_DMABUF the port (input only) negotiates\n DMABUF frames; its pwf_filter_port_buffer.data is NULL and planes are\n read via pwf_filter_port_get_dmabuf_planes().\n\n @param filter    The filter to add the port to, not yet started.\n @param direction PWF_FILTER_PORT_INPUT or PWF_FILTER_PORT_OUTPUT.\n @param config    The requested width, height, pixel format, and frame rate.\n @param opts      Per-port options, or NULL for AUTO.\n @return The new port handle, or NULL for DMABUF on an output port or an unsupported/invalid request."]
    pub fn pwf_filter_add_video_port_ex(
        filter: *mut pwf_filter,
        direction: pwf_filter_port_direction,
        config: *const pwf_video_config,
        opts: *const pwf_filter_port_opts,
    ) -> *mut pwf_filter_port;
}
unsafe extern "C" {
    #[doc = " @brief Fills up to `planes_len` entries of `planes` with the current\n        cycle's DMABUF frame layout for `buf`.\n\n Valid only during the processing callback. `planes` comes before\n `planes_len`, its own capacity, rather than after, keeping the array\n and its capacity adjacent even though `planes` is the out-parameter\n here.\n\n @param[in]  buf        The port buffer to read, from this cycle's pwf_filter_process_func_t.\n @param[out] planes     Filled with up to `planes_len` planes, most-significant plane first.\n @param[in]  planes_len Capacity of `planes`.\n @return The plane count actually available, which may exceed `planes_len` if it was too small; 0 for a non-DMABUF port or a cycle with no buffer, and `planes` is left unwritten."]
    pub fn pwf_filter_port_get_dmabuf_planes(
        buf: *const pwf_filter_port_buffer,
        planes: *mut pwf_dmabuf_plane,
        planes_len: usize,
    ) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Enables (or disables) single-buffer \"hold\" on an input `port`.\n\n On a cycle where the port receives no new data, its most recent buffer\n is re-presented (same DMABUF fd) with pwf_filter_port_buffer.fresh ==\n false, instead of reporting no buffer. Exactly one buffer is retained.\n Must be called before pwf_filter_start().\n\n @param port   An input port, not yet started.\n @param enable true to re-present the last buffer on an empty cycle, false to report no buffer instead.\n @return PWF_OK, or PWF_ERR_INVALID_ARG for a NULL or output port, or a filter already started."]
    pub fn pwf_filter_port_set_hold(port: *mut pwf_filter_port, enable: bool)
    -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Records a preferred maximum bundling period in nanoseconds,\n        offered to the graph as a requested latency at connect time.\n\n A duration, which PipeWire rescales to the graph clock; it never\n forces the graph's clock or driver. 0 clears the hint. Must be called\n before pwf_filter_start().\n\n @param filter        The filter to configure, not yet started.\n @param max_period_ns Preferred maximum bundling period in nanoseconds, or 0 to clear the hint.\n @return PWF_OK, or PWF_ERR_INVALID_ARG for a NULL filter or one already started."]
    pub fn pwf_filter_set_period_hint(
        filter: *mut pwf_filter,
        max_period_ns: u32,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Links an input `port` straight to a source node, needing no\n        external tool or session manager.\n\n Must be called after pwf_filter_start(), unlike the other port calls,\n because the target is looked up in the running graph. Blocks until the\n link negotiates, which is why it is refused from the filter's own callbacks.\n\n @param port   An input port on a started filter.\n @param target A node name, an object.serial, or \"node:port\"; naming only a node lets PipeWire pick a compatible port.\n @return PWF_OK, or an enum pwf_error: NOT_CONFIGURED before start, INVALID_ARG for a bad port or target string or an already-linked port, NOT_FOUND for a target naming no node or port, IN_CALLBACK from inside a callback, INVALID_FORMAT when the link fails to negotiate, TIMEOUT when it does not negotiate in time, NO_MEMORY when an allocation fails, CONNECT_FAILED when the link cannot be created."]
    pub fn pwf_filter_port_link(
        port: *mut pwf_filter_port,
        target: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Releases the link created on `port`, which is only needed to\n        re-target it while running; stop and destroy release every\n        link themselves.\n @param port The linked port to unlink.\n @return PWF_OK, or an enum pwf_error when the port has no link or the call comes from the process callback."]
    pub fn pwf_filter_port_unlink(port: *mut pwf_filter_port) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Adds one signal port (input or output) to `filter` — a\n        continuous channel of raw 32-bit float values, one value per\n        frame of each processing cycle (matching how audio port\n        buffers are sized).\n\n No format configuration is needed. Same timing and failure behavior\n as pwf_filter_add_audio_port().\n\n @param filter    The filter to add the port to, not yet started.\n @param direction PWF_FILTER_PORT_INPUT or PWF_FILTER_PORT_OUTPUT.\n @return The new port handle, or NULL on invalid arguments."]
    pub fn pwf_filter_add_signal_port(
        filter: *mut pwf_filter,
        direction: pwf_filter_port_direction,
    ) -> *mut pwf_filter_port;
}
unsafe extern "C" {
    #[doc = " @brief Adds one event port (input or output) to `filter` — carries\n        zero or more discrete struct pwf_event items per processing cycle\n        instead of a raw buffer.\n\n No format configuration is needed. Same timing and failure behavior\n as pwf_filter_add_audio_port().\n\n @param filter    The filter to add the port to, not yet started.\n @param direction PWF_FILTER_PORT_INPUT or PWF_FILTER_PORT_OUTPUT.\n @return The new port handle, or NULL on invalid arguments."]
    pub fn pwf_filter_add_event_port(
        filter: *mut pwf_filter,
        direction: pwf_filter_port_direction,
    ) -> *mut pwf_filter_port;
}
unsafe extern "C" {
    #[doc = " @brief Returns the media kind `port` was added with (AUDIO/VIDEO/\n        SIGNAL/EVENT).\n\n Valid for any port handle obtained from any add_*_port() call.\n\n @param port The port to query.\n @return The enum pwf_data_type `port` was added as."]
    pub fn pwf_filter_port_get_type(port: *mut pwf_filter_port) -> pwf_data_type;
}
unsafe extern "C" {
    #[doc = " @brief Returns the number of events available on `port` (an input\n        event port) for the current processing cycle.\n\n Valid only during the processing callback.\n\n @param port An input event port.\n @return The event count for this cycle; 0 if none."]
    pub fn pwf_filter_port_get_event_count(port: *mut pwf_filter_port) -> usize;
}
unsafe extern "C" {
    #[doc = " @brief Reads the event at `index` (0-based, cycle-delivery order) on\n        `port` (an input event port) into `*out`.\n\n An item of a control kind this library doesn't recognize is still\n returned, as PWF_EVENT_UNKNOWN. Valid only during the processing\n callback; `out`'s data/key pointers are valid only for that same call.\n\n @param[in]  port  An input event port.\n @param[in]  index 0-based index into this cycle's delivered events.\n @param[out] out   Filled with the event at `index`.\n @return PWF_OK, or an enum pwf_error (invalid index, or wrong port kind/direction)."]
    pub fn pwf_filter_port_get_event(
        port: *mut pwf_filter_port,
        index: usize,
        out: *mut pwf_event,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Adds one event to `port`'s event queue; the library copies\n        `event`'s data.\n\n Behavior depends on `port`'s direction:\n   - Output port: appends to the current processing cycle's outgoing\n     events, published when the cycle ends. Must be called only from\n     within the processing callback (its capacity is bounded by that\n     cycle's negotiated buffer).\n   - Input port: stages the event for delivery on the filter's next\n     processing cycle, without creating any PipeWire-level connection\n     — the event-port equivalent of pwf_filter_push_port_data(), for\n     application code (for example, a test or another in-process\n     source) to feed an event port directly. Callable anytime, not\n     just from within the processing callback.\n\n @param port  The event port to push to.\n @param event The event to copy and enqueue.\n @return PWF_OK, PWF_ERR_INVALID_ARG (wrong port kind, an invalid/unrecognized PROPERTY key, or — output ports only — no room left in the current cycle's buffer), or PWF_ERR_NO_MEMORY when the event cannot be copied."]
    pub fn pwf_filter_port_push_event(
        port: *mut pwf_filter_port,
        event: *const pwf_event,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Stages `size` bytes from `data` for `port` (an input port) to\n        be delivered on the filter's next processing cycle, without\n        creating any PipeWire-level connection.\n\n Lets application code (for example, a capture stream's data callback)\n feed a filter directly. Only the most recently pushed buffer per port\n is kept. Not valid for event ports — use pwf_filter_port_push_event()\n instead. A cycle that begins while another push to the filter is still\n being copied leaves the staged data to the cycle after it, never waiting.\n\n @param filter The filter owning `port`.\n @param port   An input, non-event port on `filter`.\n @param data   Bytes to stage; copied by the library.\n @param size   Bytes at `data`.\n @param pts    Carried through unchanged to that cycle's pwf_filter_port_buffer.pts; pass -1 if the source has no timestamp (e.g. pwf_stream_data_func_t's own `pts` when bridging a capture stream into a filter).\n @return PWF_OK, PWF_ERR_INVALID_ARG for a bad filter, port or data, or PWF_ERR_NO_MEMORY when the push buffer cannot grow."]
    pub fn pwf_filter_push_port_data(
        filter: *mut pwf_filter,
        port: *mut pwf_filter_port,
        data: *const ::core::ffi::c_void,
        size: usize,
        pts: i64,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Starts processing. Fails if the filter has zero ports.\n\n Safe to call again after stop(). It is refused from the process callback.\n\n @param filter The filter to start.\n @return PWF_OK, or an enum pwf_error."]
    pub fn pwf_filter_start(filter: *mut pwf_filter) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Stops processing; the filter may be restarted via pwf_filter_start().\n\n With `drain` true, blocks until every buffer already queued has\n actually been sent out an output port or handed to the processing\n callback on an input port, so nothing already queued is lost. If\n that does not complete within a few seconds, a warning is logged\n and the filter stops anyway. It is refused from the process callback, and a\n draining stop from the error callback too.\n\n @param filter The filter to stop.\n @param drain  true to wait for what is already queued to finish first.\n @return PWF_OK, or an enum pwf_error."]
    pub fn pwf_filter_stop(filter: *mut pwf_filter, drain: bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Releases all resources owned by `filter`, including its ports\n        and its internal thread-loop/context, whether or not it was\n        running.\n\n `filter` and any of its port handles are invalid after this returns.\n Called from inside one of the filter's own callbacks it only logs, and the\n filter is left as it was.\n\n @param filter The filter to destroy; NULL is a no-op."]
    pub fn pwf_filter_destroy(filter: *mut pwf_filter);
}
